name: "Deploy Cloud Function"
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 * * * *"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  setup-and-deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          # Cloud function name
          name: "ETL-function"
          runtime: "Python312"
          source_dir: "etl"
          entry_point: "main"
          environment_variables: "API_KEY=${{ env.API_KEY }}"
